config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :sneks, only: [:index, :create, :show, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snek.rb
class Snek < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :user

  validates :user, presence: true

  validates :name, presence: true
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :sex, inclusion: { in: %w(Male Female) }, allow_blank: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sneks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/sneks_controller.rb
class SneksController < ApplicationController
  before_action :authenticate_user!

  def index
    @sneks = current_user.sneks.order(:name)
    @snek = Snek.new
  end

  def create
    @snek = Snek.new(snek_params)
    @snek.user = current_user
    if @snek.save
      redirect_to @snek, notice: "#{@snek.name} succsessssfully created."
    else
      redirect_back(fallback_location: sneks_path, flash: { error: "Oh heck we fucked up. #{@snek.errors.full_messages.to_sentence}" })
    end
  end

  def show
    @snek = Snek.find(params[:id])
  end

  def update
    @snek = Snek.find(params[:id])
    if @snek.update(snek_params)
      redirect_to @snek, notice: "Snek succsessssfully updated."
    else
      redirect_to @snek, error: "Oh heck we fucked up."
    end
  end

  def destroy
    @snek = Snek.find(params[:id])
    name = @snek.name
    @snek.destroy
    redirect_to index, notice: "#{name} removed :("
  end

  private

  def snek_params
    params.require(:snek).permit(:name, :avatar, :remove_avatar, :sex, :age, :species, :morph, :adoption_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Home

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no, user-scalable=no, maximum-scale=1")
    %title Snekcellent
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %script{ src: "https://use.fontawesome.com/3e237d1386.js" }
  %body
    .navbar.navbar-inverse.bg-inverse#top-bar
      = link_to 'Snekcellent', root_path, class: "navbar-brand mb-0 text-center"
    .container#content-container
      - if flash[:notice]
        .alert.alert-info.alert-dismissable.fade.show
          %button.close{ "aria-label" => "Close", "data-dismiss" => "alert", :type => "button" }
            %span{ "aria-hidden" => "true" } &times;
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-warning.alert-dismissable.fade.show
          %button.close{ "aria-label" => "Close", "data-dismiss" => "alert", :type => "button" }
            %span{ "aria-hidden" => "true" } &times;
          = flash[:alert]
      - if flash[:error]
        .alert.alert-danger.alert-dismissable.fade.show
          %button.close{ "aria-label" => "Close", "data-dismiss" => "alert", :type => "button" }
            %span{ "aria-hidden" => "true" } &times;
          = flash[:error]
      = yield
    - if user_signed_in?
      %nav.navbar-light.bg-faded
        .container
          %ul.nav.nav-pills.nav-justified
            %li.nav-item
              = link_to root_path, class: "nav-link" do
                %i.fa.fa-pencil-square-o.fa-2x{ "aria-hidden" => "true" }
            %li.nav-item
              %a.nav-link{href: '#'}
                %i.fa.fa-history.fa-2x{ "aria-hidden" => "true" }
            %li.nav-item
              = link_to image_tag('noun_200416_cc.svg', class: "sneks-nav-link"), sneks_path, class: "nav-link"
            %li.nav-item.dropup
              %a.nav-link.dropdown-toggle{ "data-toggle" => "dropdown",
                                            role: "button",
                                            "aria-haspopup" => "true",
                                            "aria-expanded" => "false",
                                            href: "#" }
                %i.fa.fa-cogs.fa-2x{ "aria-hidden"=> "true" }
              .dropdown-menu.dropdown-menu-right
                %a.dropdown-item{ href: "#" }
                  Account Settings
                = link_to 'Sign out', destroy_user_session_path,
                  method: :delete, class: "dropdown-item" if user_signed_in?

app/views/sneks/_form.html.haml
.modal.fade#snekForm{ "aria-hidden" => "true" }
  .modal-dialog.modal-lg
    .modal-content
      = form_for @snek do |f|
        .modal-header
          %h5.modal-title
            Tell me ’bout your snek
          %button.close{ "type" => "button", "data-dismiss" => "modal", "aria-label" => "Close" }
            %span{ "aria-hidden" => "true" } &times;
        .modal-body
          .form
            .form-group
              = f.label :name, { class: "form-control-label"}
              = f.text_field :name, { class: "form-control", required: "true", oninvalid: "this.setCustomValidity('Name yer snek, dood.')"}

              Sneaky Avatar
              %br
              -# trying to style this with bootstrap but fucking failng...

              -# .fileinput.fileinput-new{ "data-provides" => "fileinput" }
              -#   .fileinput-preview.thumbnail{ "data-trigger" => "fileinput", "style" => "width: 200px; height: 150px;" }
              -#     %span.btn.btn-default.btn-file
              -#       %span.fileinput-new
              -#         Select image
              -#         %span.fileinput-exists
              -#           Change
              -#           %input{ type: "file", name: "..." }
              -#     %a.btn.btn-default.fileinput-exists{"href" => "#", "data-dismiss" => "fileinput" } Remove

              -# %label.custom-file
              -#   %input.custom-file-input#file{ name: 'snek[avatar]', type: 'file' }
              -#   %span.custom-file-control

              = f.file_field :avatar
              - if f.object.avatar?
                = image_tag f.object.avatar.thumb
                = f.label :remove_avatar
                = f.check_box :remove_avatar
              = f.hidden_field :avatar_cache

              -# %input.btn.btn-primary{type: 'file'}
              %br

              Sex
              %br
              %label.custom-control.custom-radio
                %input.custom-control-input#snek_sex_male{ name: 'snek[sex]', value: 'Male', type: 'radio' }
                %span.custom-control-indicator
                %span.custom-control-description Male

              %label.custom-control.custom-radio
                %input.custom-control-input#snek_sex_female{ name: 'snek[sex]', value: 'Female', type: 'radio' }
                %span.custom-control-indicator
                %span.custom-control-description Female
              %br
              = f.label :age, { class: "form-control-label" }
              = f.number_field :age, { class: "form-control" }

              = f.label :species, { class: "form-control-label" }
              = f.text_field :species, { class: "form-control" }

              = f.label :morph, { class: "form-control-label" }
              = f.text_field :morph, { class: "form-control" }

              = f.label :adoption_date, 'Adoption Date', { class: "form-control-label" }
              = f.date_field :adoption_date, { class: "form-control" }

        .modal-footer
          %button.btn.btn-secondary{ "data-dismiss" => "modal" } Close
          = f.submit 'Dat my snek!', { class: "btn btn-primary" }

app/views/sneks/index.html.haml
.row
  .col
    %h3.page-title Your Sneks
- if @sneks.empty?
  .row
    .col
      %p You have no sneks!
- else
  .row
    - @sneks.each do |snek|
      .col-5.mb-3
        = link_to snek do
          .card.text-center.card-button
            .card-block
              .card-title= snek.name
.row
  .col-5.mb-3
    .card.text-center.card-button#new-snek{ "data-toggle" => "modal", "data-target" => "#snekForm" }
      .card-block
        .card-title +1 Snek!

  = render partial: 'form'

app/views/sneks/show.html.haml
.row
  .col
    %h3.page-title.text-center= @snek.name
.row
  .col
    = image_tag @snek.avatar, { class: 'img-thumbnail avatar' }
    %h5 Age
    = "#{@snek.age}"
    %h5= "Sex: #{@snek.sex}"
    %h5= "Species: #{@snek.species}"
    %h5= "Morph: #{@snek.morph}"
    %h5= "Adoption Date: #{@snek.adoption_date}"
.row
  .col
    %button.btn.btn-primary{ "data-toggle" => "modal", "data-target" => "#snekForm" } Edit Snek

    = link_to 'Remove Snek', snek_path(@snek), method: :delete, data: { confirm: "OH GAWD WHY? ARE YOU SURE? YOU CAN'T UNDO THIS, DOOD."}, class: "btn btn-danger", id: "snek-delete"

= render partial: 'form'